## login
POST localhost:8484/login
Content-Type: application/json

{
  "email" : "petya.peteva2@gmail.com",
  "pass" : "Aa@!l123"
}

### register
POST localhost:8484/users
Content-Type: application/json

{
  "email" : "petygm@gmail.com",
  "password" : "Aa@!lkjl123",
  "firstName" : "Petya"

}

### get by id
GET localhost:8484/test_table/1
Content-Type: application/json

### edit
PUT localhost:8484/test_table
Content-Type: application/json

{
  "id" : 1,
  "username" : "petyaa",
  "password" : "123",
  "confirmPassword" : "123"
}


### gelete
DELETE localhost:8484/test_table/1
Content-Type: application/json

### logout
POST localhost:8484/test_table
