### editProfile
PUT localhost:8484/user/edit/profile
Content-Type: application/json

{
  "userId": 2,
  "email": "s.g.sevdeva@gmail.com",
  "firstName": "Sanya",
  "middleName": "G.",
  "lastName": "Sevdeva",
  "gender": "f",
  "username": "ssevdeva",
  "showLastName": false,
  "isReverseNameOrder": false,
  "genderViewableBy": "f",
  "locationViewableBy": "f",
  "dateOfBirth": "2002-11-01",
  "address": {
    "addressId": 2,
    "townName": "Gotse Delchev"
  }
}

### editPrivacy
PUT localhost:8484/user/edit/privacy
Content-Type: application/json

{
  "userId": 2,
  "privacy": {
    "privacyId": 2,
    "viewProfile": "e",
    "canNonFriendsFollow": true,
    "canNonFriendsComment": true,
    "canDisplayReviews": true,
    "privateMessages": true,
    "isEmailVisible": true,
    "allowSearchByEmail": true,
    "challengeQuestion": "Hello dear?",
    "promptToRecommendBooks": true
  }
}

### changePassword
PUT localhost:8484/user/edit/password
Content-Type: application/json

{
  "userId": 1,
  "currentPassword": "Aa@!lkjl123",
  "newPassword": "Aa@!lkjl1234",
  "confirmPassword": "Aa@!lkjl1234"
}

### login
POST localhost:8484/login
Content-Type: application/json

{
  "email" : "petygm@gmail.com",
  "password" : "Aa@!lkjl123"
}

### login
POST localhost:8484/login
Content-Type: application/json

{
  "email" : "s.g.sevdeva@gmail.com",
  "password" : "sanyAsevdev@22"
}

### register
POST localhost:8484/users
Content-Type: application/json

{
  "email" : "petygm@gmail.com",
  "password" : "Aa@!lkjl123",
  "firstName" : "Petya"

}

### register
POST localhost:8484/users
Content-Type: application/json

{
  "email" : "s.g.sevdeva@gmail.com",
  "password" : "sanyAsevdev@22",
  "firstName" : "Sanya"

}